-- Add new columns to transactions table
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS pack_name VARCHAR,
ADD COLUMN IF NOT EXISTS credits_added INTEGER,
ADD COLUMN IF NOT EXISTS previews_added INTEGER,
ADD COLUMN IF NOT EXISTS amount_paid DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS currency VARCHAR DEFAULT 'USD',
ADD COLUMN IF NOT EXISTS invoice_url VARCHAR,
ADD COLUMN IF NOT EXISTS file_name VARCHAR,
ADD COLUMN IF NOT EXISTS download_url VARCHAR,
ADD COLUMN IF NOT EXISTS expiration_time TIMESTAMP WITH TIME ZONE; 